steps:

- id: "ls -la"
  name: 'bash'
  env: ['GOPATH=go-http-server']
  args: ['ls', '-la']

- id: "Run tests"
  name: 'gcr.io/cloud-builders/go'
  env: ['GOPATH=go-http-server']
  args: ['test', 'challenge05', '-v', '-cover']

- id: "Building docker image"
  name: 'gcr.io/cloud-builders/docker'
  args: ["build", "-t", "axell13/microservices-devops-challenge05-go", "."]

- id: "Uploading docker image"
  name: 'gcr.io/cloud-builders/docker'
  args: ["push", "axell13/microservices-devops-challenge05-go"]
