apiVersion: apps/v1
kind: Deployment
metadata:
  name: challenge05-hello-nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: challenge05-hello-nginx
  template: # inside template we will have a pod specification
    metadata:
      labels:
        app: challenge05-hello-nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.17-alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /etc/nginx/conf.d
              readOnly: true
              name: challenge05-nginx-conf
      volumes:
        - name: challenge05-nginx-conf
          configMap:
            name: challenge05-nginx-conf
            items:
              - key: nginx.conf
                path: nginx.conf
