apiVersion: apps/v1
kind: Deployment
metadata:
  name: challenge05-mysql-server
spec: # Deployment spec
  replicas: 1
  selector: # Selector used to create the service
    matchLabels:
      app: challenge05-mysql-server
      tier: db
  template: # POD template
    metadata:
      labels:
        app: challenge05-mysql-server
        tier: db
    spec: # POD spec
      containers:
      - image: mysql:5.7
        name: challenge05-mysql-server
        args:
          - "--ignore-db-dir=lost+found"
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        ports:
        - containerPort: 3306
        volumeMounts: # Attach POD's volumes to the container 
        - name: challenge05-mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes: # Define POD volumes
      - name: challenge05-mysql-persistent-storage
        persistentVolumeClaim:
          claimName: challenge05-mysql-persistent-volume-claim